# Generated by Django 3.2.23 on 2023-12-10 22:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_emailverification'),
    ]

    operations = [
        migrations.AddField(
            model_name='emailverification',
            name='verification_token',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
