# Generated by Django 3.2.23 on 2023-12-11 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_delete_customuser'),
    ]

    operations = [
        migrations.AddField(
            model_name='emailverification',
            name='email',
            field=models.EmailField(default='', max_length=254),
        ),
    ]
